[project]
name = "minigrad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.21",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "torch>=2.14.0",
]

[project.scripts]
minigrad = "minigrad:main"
[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
